yamlformat:
  pattern: ^([a-z]+)\(([a-zA-Z0-9_-]+)\):\s.+
  types:
  - build
  - chore
  - ci
  - config
  - docs
  - feat
  - fix
  - merge
  - perf
  - refactor
  - release
  - revert
  - security
  - style
  - test
  scopes:
  - api
  - db
  - auth
  - ui
  - core
  - repo
  - deps
  - tests
  - cli
  - docs
  - config
  - scripts
  - assets
  - integration
  - deployment
  - logging
  - monitoring
  - cache
